name: world-models
channels:
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pytorch=2.0
  - pytorch-cuda=11.8
  - wandb=0.15
  - hydra-core=1.3
  - hydra-submitit-launcher=1.2
  - gpytorch=1.11  # Needed for the SVGP transition/reward models
  - laplace-torch==0.1a2 # For Laplace transition model
  - imageio  # For VideoRecorder in utils/video.py
  - moviepy  # For VideoRecorder in utils/video.py
  - pip
  - pip:
      - jaxtyping==0.2.23  # Types with shapes for tensors
      - dm_control==1.0.15  # Handles mujoco installation
      - jaxtyping
      # - numpy
      # - gymnasium
      # - imageio
      # - umap
      - vector_quantize_pytorch
      # experiments
      # - moviepy
