defaults:
  - base_tae_ddpg
_target_: src.agents.TAEDDPG

# mlp_dims: [256, 256]
mlp_dims: [128, 128]
exploration_noise: 0.2
policy_noise: 0.2
noise_clip: 0.5
learning_rate: 3e-4
batch_size: 512
num_updates: 1000 # 1000 is 1 update per new data
# actor_update_freq: 2  # update actor less frequently than critic
# nstep: 3
gamma: 0.99
tau: 0.005
device: ${device}
name: "TAE-DDPG"

vae_learning_rate: 3e-4
vae_batch_size: 256
# vae_num_updates: 2000
vae_num_updates: 20000
vae_patience: 100
vae_min_delta: 0.0
# vae_num_updates: 200
# vae_num_updates: 5000
latent_dim: 20
# latent_dim: 4
