defaults:
  - base_vae_ddpg
_target_: src.agents.VAEDDPG
# _convert_: all

mlp_dims: [256, 256]
exploration_noise: 0.2
policy_noise: 0.2
noise_clip: 0.5
learning_rate: 3e-4
batch_size: 512
num_updates: 1000 # 1000 is 1 update per new data
# actor_update_freq: 2  # update actor less frequently than critic
# nstep: 3
gamma: 0.99
tau: 0.005
device: ${device}
name: "VAE-DDPG"

vae_learning_rate: 3e-4
vae_batch_size: 256
vae_num_updates: 2000
# vae_num_updates: 5000
# latent_dim: 20
latent_dim: 4
