_target_: "agents.DDPG"
# DDPG stuff
mlp_dims: [256, 256]
exploration_noise: 1.0
policy_noise: 0.2
noise_clip: 0.3
learning_rate: 3e-4
batch_size: 256
# num_updates: int = 1000  # 1000 is 1 update per new data
utd_ratio: 1  # parameter update-to-data ratio
actor_update_freq: 2  # update actor less frequently than critic
# nstep: 3
discount: 0.99
tau: 0.005
device: ${device}
# Reset stuff
reset_params_freq: 100000  # reset params after this many param updates
name: DDPG_reset-freq=${agent.reset_params_freq}_utd=${agent.utd_ratio}
