_target_: "agents.TD3"
# TD3 stuff
mlp_dims: [512, 512]
exploration_noise_start: 1.0
exploration_noise_end: 0.1
exploration_noise_num_steps: 50
policy_noise: 0.2
noise_clip: 0.3
learning_rate: 3e-4
batch_size: 256
utd_ratio: 1  # parameter update-to-data ratio
actor_update_freq: 2  # update actor less frequently than critic
nstep: 1
gamma: 0.99
tau: 0.005
device: ${device}
# Reset stuff
reset_type: "full" # "full" or "last-layer"
reset_params_freq: None # reset params after this many param updates
# reset_params_freq: 100000  # reset params after this many param updates
name: TD3_reset-freq=${agent.reset_params_freq}_reset_type=${agent.reset_type}_utd=${agent.utd_ratio}
