_target_: "agents.VQ_TC_TD3"
# Actor/critic stuff
mlp_dims: [512, 512]
# exploration_noise: 1.0
exploration_noise_start: 1.0
exploration_noise_end: 0.1
exploration_noise_num_steps: 50
policy_noise: 0.2
noise_clip: 0.3
learning_rate: 3e-4
batch_size: 256
utd_ratio: 1  # parameter update-to-data ratio
actor_update_freq: 2  # update actor less frequently than critic
nstep: 1
horizon: 1
discount: 0.99
tau: 0.005
device: ${device}
# Reset stuff
reset_type: "full" # "full" or "last-layer"
reset_strategy: "latent-dist"  #  "latent-dist" or "every-x-param-updates"
reset_params_freq: 100000  # reset params after this many param updates
reset_threshold: 0.01  # reset latent (z) when changed by more than this
memory_size: 10000  # mem size for calculating ||z_{mem} - e_{\phi}(x_mem)||
# AE config
train_strategy: "interleaved"  # "interleaved" or "representation-first"
temporal_consistency: True # if True include dynamic model in encoder
reconstruction_loss: False # if True include decoder
use_cosine_similarity_dynamics: False
use_target_encoder: False
act_with_target_enc: False
encoder_mlp_dims: [256]
ae_learning_rate: 1e-4
ae_batch_size: 256
ae_utd_ratio: 1  # encoder parameter update-to-data ratio
ae_patience: 100
ae_min_delta: 0.0
latent_dim: 512
ae_tau: 0.005
ae_normalize: True
simplex_dim: 8
use_fsq: True
fsq_num_codes: 1024
fsq_levels: [8, 6, 5]
fsq_idx: 0
# encoder_reset_params_freq: int = 10000  # reset enc params after X param updates
name: VQ-TC-TD3_n=${agent.nstep}_h=${agent.horizon}_td3-targ=${agent.use_target_encoder}_act-targ=${agent.act_with_target_enc}_cos=${agent.use_cosine_similarity_dynamics}_${agent.reset_strategy}-${agent.reset_type}_${agent.train_strategy}-${agent.reset_params_freq}_temp-${agent.temporal_consistency}_rec=${agent.reconstruction_loss}_utd=${agent.utd_ratio}_${agent.fsq_levels}_idx=${agent.fsq_idx}
